### PR TITLE
Implement Custom GitHub Actions

### PR DESCRIPTION
**Pull request by EngineerDanny**
This PR intends to create Github Actions to make it easier for package developers to use Rperform to test their code.
The Actions are tested on a separate repository [stringr](https://github.com/EngineerDanny/stringr/pull/2).

### CODE REVIEW

**Comment by EngineerDanny** [comment]
The Github workflow directory, which is the `.github/workflow/` directory, is created automatically when you ran 
`Rperform::init_rperform()` function. It is also populated with the needed workflow files to be able to run `Rperform` with ease. It also adds the `rperform` directory and populates it with files which make test configuration and customisation easier. One of the most important files in that directory is the `script.R` file which is where the Rperform test functions should be written.
Screenshot 2022-07-01 at 3 33 40 PM
This is still work in progress. For now, I only tested it with the `plot_metrics`. More updates will follow.

**Comment by EngineerDanny** [comment]
The Github workflow directory, which is the `.github/workflow/` directory, is created automatically when you ran 
`Rperform::init_rperform()` function. It is also populated with the needed workflow files to be able to run `Rperform` with ease.

**Comment by EngineerDanny** [comment]
I had an issue with the Github create comment script which was similar to [this issue](https://github.com/actions/github-script/issues/77). After several debugging and testing, I have been able to successfully automate the creation of comments. [(Auto Comment On PR)](https://github.com/EngineerDanny/stringr/pull/2#issuecomment-1172716652).
Testing results are firstly uploaded as an artifact on Github.
Then afterwards, a comment is created by Github actions bot on the PR.

**Comment by EngineerDanny** [comment]
Another minor update is that this PR addresses is the x-axis theme. Now, it is diagonal (-45°) instead of straight vertical(-90°).

Screenshot 2022-07-01 at 10 06 46 PM

**Comment by tdhock** [comment]
this is good progress but I think the screenshot of the plot is cut off / cropped?
You may want to further adjust the hjust/vjust of the x axis tick text.

**Comment by EngineerDanny** [comment]
@tdhock Sure, I will adjust the x axis tick text in my next update.

**Comment by tdhock** [comment]
can you please share what the updated plots/results would look like for the user?

**Comment by EngineerDanny** [comment]
@tdhock Yes. This is an [example comment.](https://github.com/EngineerDanny/stringr/pull/4#issuecomment-1183558828)
It is very much customisable. I included `header.R` and `footer.R` files which the user can customise to edit the general comment output.

**Comment by EngineerDanny** [comment]
@tdhock Great feedback. Since all the comments you raised target mostly the `ggplot` graph output,  I am going to close this PR and proceed with submitting another PRs to fix them accordingly.

**Comment by tdhock** [comment]
great

**Pull request merged**
